name: demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Basic UI
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.12.1

  

  # Image and camera utilities
  image_picker: ^1.1.2
  camera: ^0.10.5
  path_provider: ^2.1.4
  path: ^1.9.0
  webview_flutter: ^4.4.2

  # Firebase core libraries (latest stable versions)
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.0
  firebase_database: ^11.1.0

  intl: ^0.19.0

  # Voice Command & Video Streaming
  speech_to_text: ^7.3.0
  audioplayers: ^5.2.1
  flutter_vlc_player: ^7.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/models/
  